name: Test action

on:
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Upload test.txt
      uses: csala/google-drive-upload-action@v1
      with:
        credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS_BASE64 }}
        target: test.txt
        parent_folder_id: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
